### ISSUE TITLE
serialization error w/ JMSEvent

### ISSUE THREAD

**Issue by mattf** [mattf/spark-streaming-jms#1]
```
$ spark-submit --jars target/scala-2.10/spark-streaming-jms-assembly-0.0.1.jar example.py
...
15/05/03 19:55:44 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15/05/03 19:55:57 WARN BlockManager: Block input-0-1430682957000 replicated to only 0 peer(s) instead of 1 peers
15/05/03 19:55:57 WARN BlockManager: Block input-0-1430682957200 replicated to only 0 peer(s) instead of 1 peers
15/05/03 19:55:57 WARN BlockManager: Block input-0-1430682957400 replicated to only 0 peer(s) instead of 1 peers
15/05/03 19:56:02 ERROR PythonRDD: Python worker exited unexpectedly (crashed)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/usr/share/spark/python/pyspark/worker.py", line 90, in main
    command = pickleSer._read_with_length(infile)
  File "/usr/share/spark/python/pyspark/serializers.py", line 145, in _read_with_length
    length = read_int(stream)
  File "/usr/share/spark/python/pyspark/serializers.py", line 521, in read_int
    raise EOFError
EOFError

    at org.apache.spark.api.python.PythonRDD$$anon$1.read(PythonRDD.scala:137)
    at org.apache.spark.api.python.PythonRDD$$anon$1.<init>(PythonRDD.scala:174)
    at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:96)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:280)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:247)
    at org.apache.spark.api.python.PythonRDD$WriterThread$$anonfun$run$1.apply$mcV$sp(PythonRDD.scala:242)
    at org.apache.spark.api.python.PythonRDD$WriterThread$$anonfun$run$1.apply(PythonRDD.scala:204)
    at org.apache.spark.api.python.PythonRDD$WriterThread$$anonfun$run$1.apply(PythonRDD.scala:204)
    at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1550)
    at org.apache.spark.api.python.PythonRDD$WriterThread.run(PythonRDD.scala:203)
Caused by: org.apache.spark.SparkException: Unexpected element type class com.redhat.spark.streaming.jms.JMSEvent
    at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:420)
    ... 5 more
15/05/03 19:56:02 ERROR PythonRDD: This may have been caused by a prior exception:
org.apache.spark.SparkException: Unexpected element type class com.redhat.spark.streaming.jms.JMSEvent
    at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:420)
    at org.apache.spark.api.python.PythonRDD$WriterThread$$anonfun$run$1.apply$mcV$sp(PythonRDD.scala:242)
    at org.apache.spark.api.python.PythonRDD$WriterThread$$anonfun$run$1.apply(PythonRDD.scala:204)
    at org.apache.spark.api.python.PythonRDD$WriterThread$$anonfun$run$1.apply(PythonRDD.scala:204)
    at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1550)
    at org.apache.spark.api.python.PythonRDD$WriterThread.run(PythonRDD.scala:203)
```

**Comment by mattf** [comment]
@davies i'm hoping to get this jms streaming example working w/ both java & python before submitting a patch to spark streaming. however, i'm having issues exposing it for pyspark. will you take a look and suggest what i'm doing wrong?

**Comment by mattf** [comment]
@andrewor14 do you have any suggestions?
